version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: wms-postgres
    environment:
      POSTGRES_DB: wmsdb
      POSTGRES_USER: wmsuser
      POSTGRES_PASSWORD: akith123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: wms-rabbit
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: wmsuser
      RABBITMQ_DEFAULT_PASS: akith123

volumes:
  pgdata:
