spring:
  application:
    name: swift-logistics-wms
    
  datasource:
    url: jdbc:postgresql://localhost:5432/wmsdb
    username: wmsuser
    password: wmspass
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: wmsuser
    password: wmspass

server:
  port: 8080

logging:
  level:
    lk.swiftlogistics.wms: DEBUG
    org.springframework.amqp: DEBUG
