spring:
  application:
    name: swift-logistics-wms
    
  datasource:
    url: jdbc:postgresql://localhost:5432/wmsdb
    username: wmsuser
    password: wmspass
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: wmsuser
    password: wmspass

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    lk.swiftlogistics.wms: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework.web: DEBUG

# CORS Configuration
cors:
  allowed-origins:
    - "http://localhost:3000"
    - "http://localhost:5173"
    - "http://127.0.0.1:3000"
    - "http://127.0.0.1:5173"
